name: pixel
version: '${project.version}'
main: kiwi.hoonkun.plugins.pixel.Entry
api-version: 1.18
authors: [ hoon_kiwicraft ]
description: 마인크래프트 맵을 git 으로 버전관리해보세요!!
commands:
  pixel:
    permission: pixel
    description: "version control the minecraft map with git!!"
    permission-message: "you dont have permission to run this command..."
    usage: "run '/pixel help' to show all available commands!"
permissions:
  pixel:
    default: op
